version: "2"

services:

  plone:
    # image: eeacms/plone-copernicus-land
    build: .
    ports:
    - "8080:8080"
    volumes:
      - land-data:/data
      - ./src:/plone/instance/src
      - ./buildout.cfg:/plone/instance/buildout.cfg
    environment:
      ZOPE_MODE: zeo_client
      LAND_DOWNLOADS_SRC_PATH: /tmp/
      LAND_DOWNLOADS_DST_PATH: /tmp/
    # this places the container in "shell mode". Run
    # "docker-compose exec plone bash" to enter the shell
    # then you can start the instance with bin/zeo_client fg
    entrypoint: sh -c "tail -f /dev/null"

  memcached:
    image: eeacms/memcached
    tty: true
    stdin_open: true

  # async:
  #   image: eeacms/plone-copernicus-land
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     ZOPE_MODE: zeo_async
  #   volumes:
  #   - /etc/localtime:/etc/localtime:ro

  zeoserver:
    image: plone/zeoserver:2.13.23
    volumes:
      - land-data:/data
    environment:
      TZ: "Europe/Copenhagen"

  cron-users-stats:
    image: eeacms/plone-copernicus-land:14.0-2.8
    labels:
      io.rancher.container.start_once: "true"
      io.rancher.scheduler.affinity:host_label: copernicus=yes
      cron.schedule: "0 4 * * *"
    environment:
      TZ: "Europe/Copenhagen"
      entrypoint: bin/zeo_client run bin/users_stats
    volumes:
      - land-data:/data

volumes:
  land-data:
