version: "2"

services:

  plone:
    # image: eeacms/plone-copernicus-land
    build: .
    ports:
    - "8080:8080"
    volumes:
      - land-data:/data
      - ./src:/plone/instance/src
      - ./buildout.cfg:/plone/instance/buildout.cfg
    environment:
      ZOPE_MODE: zeo_client
      LAND_DOWNLOADS_SRC_PATH: /tmp/
      LAND_DOWNLOADS_DST_PATH: /tmp/
    # this places the container in "shell mode". Run
    # "docker-compose exec plone bash" to enter the shell
    # then you can start the instance with bin/zeo_client fg
    entrypoint: sh -c "tail -f /dev/null"

  # async:
  #   image: eeacms/plone-copernicus-land
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     ZOPE_MODE: zeo_async
  #   volumes:
  #   - /etc/localtime:/etc/localtime:ro

  zeoserver:
    image: plone/zeoserver:2.13.23
    volumes:
      - land-data:/data
    environment:
      TZ: "Europe/Copenhagen"

volumes:
  land-data:
